project: 
  type: website
  output-dir: docs

profile:
  default: english
  group: [english, french]

format:
  html: 
    theme: cosmo
    toc: true
    css: styles/custom.css
    
execute:
  freeze: auto